### PR TITLE
Micvbang/extractor rocksdb

### PR DESCRIPTION
**Pull request by micvbang**
@safl  A first take on implementing a RocksDB db_bench extractor.

This is just to align on the implementation of the extractor itself, which we'll move to a different package afterwards, as discussed.

### CODE REVIEW

**Comment by micvbang** [comment]
Example `metrics.yml` generated from the following `db_bench` output

```
Initializing RocksDB Options from the specified file
Initializing RocksDB Options from command-line flags
RocksDB:    version 6.18
Date:       Wed Mar  3 15:40:16 2021
CPU:        16 * AMD Ryzen 7 PRO 4750U with Radeon Graphics
CPUCache:   512 KB
Keys:       16 bytes each ( 0 bytes user-defined timestamp)
Values:     100 bytes each (50 bytes after compression)
Entries:    1000000
Prefix:    0 bytes
Keys per prefix:    0
RawSize:    110.6 MB (estimated)
FileSize:   62.9 MB (estimated)
Write rate: 0 bytes/second
Read rate: 0 ops/second
Compression: Snappy
Compression sampling rate: 0
Memtablerep: skip_list
Perf Level: 1
------------------------------------------------
Initializing RocksDB Options from the specified file
Initializing RocksDB Options from command-line flags
DB path: [/tmp/rocksdbtest-1000/dbbench]
fillseq      :       1.789 micros/op 559021 ops/sec;   61.8 MB/s
Please disable_auto_compactions in FillDeterministic benchmark
```

```yml
---
- bwps: 64801996.8
  ctx:
    compression: Snappy
    date: Wed Mar  3 15:40:16 2021
    entries: 1000000.0
    evars:
      CMD_PREFIX: ' '
      FIO_AUX: ''
      FIO_BIN: /opt/aux/fio
      FIO_BS_LIST: '512'
      FIO_IODEPTH_LIST: 1 2 4 8 16
      FIO_IOENG_NAME: xnvme
      FIO_NRUNS: '1'
      FIO_RW: randread
      FIO_SCRIPT: xnvme-compare.fio
      FIO_SECTION: override
      NVME_NSTYPE: lblk
      XNVME_BE: spdk
    extractor_name: rocksdb_db_bench
    fname: db_bench.txt
    keys_bytes: 16.0
    memtable_rep: skip_list
    rocks_ver: '6.18'
    values_bytes: 100.0
  iops: 559021.0
  lat: 0.001789
```

**Comment by safl** [comment]
This looks pretty good, a quick thought: it should probably be added to it's own package e.g. ``cijoe-pkg-rocksdb`` for testcases, extractors etc. specific to RocksDB.
I would like to reduce the application specific stuff to be provided via packages keeping the ``cijoe`` minimal. It is currently super bloated with various modules and wrappers specific to Linux, this ought to be removed as well :)

**Comment by micvbang** [comment]
Yeah, sounds good. I did look into this already, but couldn't find a nice way to do this. It felt natural to use "implicit namespace packages" (https://www.python.org/dev/peps/pep-0420), but since the `extractors` directory isn't empty (it already holds the fio implementation) I don't think implicit namespace packages are going to work.

Do you have any ideas?

**Comment by micvbang** [comment]
Closing as we decided to use implicit namespace packages and have moved this to a separate `cijoe-pkg-rocksdb` package

**Pull request closed without merging**
